BEGIN;

DO $$
DECLARE
  target_schema text;
  seq_regclass text;
  idx_rel_lp text;
  idx_rel_pg text;
  idx_cod_interno text;
  has_identity boolean;
  has_sequence_default boolean;
BEGIN
  FOR target_schema IN SELECT unnest(ARRAY['venta','compra']) LOOP
    seq_regclass := format('%I.%I', target_schema, 'productos_gampack_id_interno_seq');
    idx_rel_lp := target_schema || '_relacion_articulos_id_lista_precios_idx';
    idx_rel_pg := target_schema || '_relacion_articulos_id_productos_gampack_idx';
    idx_cod_interno := target_schema || '_productos_gampack_cod_interno_idx';

    -- Asegurar esquema y search_path
    EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', target_schema);
    PERFORM set_config('search_path', format('%I,public', target_schema), true);

    -- Renombrar tabla antigua si aún persiste
    IF EXISTS (
      SELECT 1
      FROM information_schema.tables
      WHERE table_schema = target_schema
        AND table_name = 'lista_interna'
    ) AND NOT EXISTS (
      SELECT 1
      FROM information_schema.tables
      WHERE table_schema = target_schema
        AND table_name = 'productos_gampack'
    ) THEN
      EXECUTE format('ALTER TABLE %I.lista_interna RENAME TO productos_gampack', target_schema);
    END IF;

    -- Asegurar tabla principal de productos
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I.productos_gampack (
         id_interno INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         cod_interno TEXT UNIQUE,
         nom_interno TEXT,
         precio_final NUMERIC,
         fecha DATE,
         mes_actualizacion TEXT
       )',
      target_schema
    );

    -- Columnas requeridas
    EXECUTE format('ALTER TABLE %I.productos_gampack ADD COLUMN IF NOT EXISTS id_interno INTEGER', target_schema);
    EXECUTE format('ALTER TABLE %I.productos_gampack ADD COLUMN IF NOT EXISTS cod_interno TEXT', target_schema);
    EXECUTE format('ALTER TABLE %I.productos_gampack ADD COLUMN IF NOT EXISTS nom_interno TEXT', target_schema);
    EXECUTE format('ALTER TABLE %I.productos_gampack ADD COLUMN IF NOT EXISTS precio_final NUMERIC', target_schema);
    EXECUTE format('ALTER TABLE %I.productos_gampack ADD COLUMN IF NOT EXISTS fecha DATE', target_schema);
    EXECUTE format('ALTER TABLE %I.productos_gampack ADD COLUMN IF NOT EXISTS mes_actualizacion TEXT', target_schema);

    -- Tipos esperados
    EXECUTE format('ALTER TABLE %I.productos_gampack ALTER COLUMN id_interno TYPE INTEGER', target_schema);
    EXECUTE format('ALTER TABLE %I.productos_gampack ALTER COLUMN cod_interno TYPE TEXT USING cod_interno::text', target_schema);
    EXECUTE format('ALTER TABLE %I.productos_gampack ALTER COLUMN nom_interno TYPE TEXT USING nom_interno::text', target_schema);
    EXECUTE format('ALTER TABLE %I.productos_gampack ALTER COLUMN precio_final TYPE NUMERIC USING precio_final::numeric', target_schema);
    EXECUTE format('ALTER TABLE %I.productos_gampack ALTER COLUMN fecha TYPE DATE USING fecha::date', target_schema);
    EXECUTE format('ALTER TABLE %I.productos_gampack ALTER COLUMN mes_actualizacion TYPE TEXT USING mes_actualizacion::text', target_schema);
    EXECUTE format('ALTER TABLE %I.productos_gampack ALTER COLUMN id_interno SET NOT NULL', target_schema);

    -- Primary key y secuencia/identidad
    has_identity := EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = target_schema
        AND table_name = 'productos_gampack'
        AND column_name = 'id_interno'
        AND is_identity = 'YES'
    );

    has_sequence_default := EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema = target_schema
        AND table_name = 'productos_gampack'
        AND column_name = 'id_interno'
        AND column_default LIKE 'nextval%'
    );

    IF NOT has_identity AND NOT has_sequence_default THEN
      EXECUTE format('CREATE SEQUENCE IF NOT EXISTS %s', seq_regclass);
      EXECUTE format(
        'ALTER TABLE %I.productos_gampack ALTER COLUMN id_interno SET DEFAULT nextval(''%s''::regclass)',
        target_schema,
        seq_regclass
      );
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.table_constraints
      WHERE table_schema = target_schema
        AND table_name = 'productos_gampack'
        AND constraint_type = 'PRIMARY KEY'
    ) THEN
      EXECUTE format('ALTER TABLE %I.productos_gampack ADD CONSTRAINT productos_gampack_pkey PRIMARY KEY (id_interno)', target_schema);
    END IF;

    -- Índice único por código interno
    EXECUTE format(
      'CREATE UNIQUE INDEX IF NOT EXISTS %I ON %I.productos_gampack (cod_interno)',
      idx_cod_interno,
      target_schema
    );

    -- Relacionar articulos -> tablas internas y lista de precios
    IF EXISTS (
      SELECT 1
      FROM information_schema.tables
      WHERE table_schema = target_schema
        AND table_name = 'relacion_articulos'
    ) THEN
      -- Drop de FKs antiguos si existiesen
      EXECUTE format('ALTER TABLE %I.relacion_articulos DROP CONSTRAINT IF EXISTS fk_rel_li', target_schema);
      EXECUTE format('ALTER TABLE %I.relacion_articulos DROP CONSTRAINT IF EXISTS fk_rel_pg', target_schema);
      EXECUTE format('ALTER TABLE %I.relacion_articulos DROP CONSTRAINT IF EXISTS relacion_articulos_id_productos_gampack_fkey', target_schema);
      EXECUTE format('ALTER TABLE %I.relacion_articulos DROP CONSTRAINT IF EXISTS relacion_articulos_productos_gampack_fk', target_schema);
      EXECUTE format('ALTER TABLE %I.relacion_articulos DROP CONSTRAINT IF EXISTS relacion_articulos_lista_precios_fk', target_schema);
      EXECUTE format('ALTER TABLE %I.relacion_articulos DROP CONSTRAINT IF EXISTS relacion_articulos_id_lista_precios_fkey', target_schema);

      EXECUTE format(
        'ALTER TABLE %I.relacion_articulos
           ADD CONSTRAINT relacion_articulos_productos_gampack_fk
           FOREIGN KEY (id_productos_gampack)
           REFERENCES %I.productos_gampack (id_interno)
           ON DELETE CASCADE',
        target_schema,
        target_schema
      );

      EXECUTE format(
        'ALTER TABLE %I.relacion_articulos
           ADD CONSTRAINT relacion_articulos_lista_precios_fk
           FOREIGN KEY (id_lista_precios)
           REFERENCES %I.lista_precios (id_externo)
           ON DELETE CASCADE',
        target_schema,
        target_schema
      );

      -- Índices para acelerar búsquedas por claves foráneas
      EXECUTE format(
        'CREATE INDEX IF NOT EXISTS %I ON %I.relacion_articulos (id_lista_precios)',
        idx_rel_lp,
        target_schema
      );
      EXECUTE format(
        'CREATE INDEX IF NOT EXISTS %I ON %I.relacion_articulos (id_productos_gampack)',
        idx_rel_pg,
        target_schema
      );
    END IF;
  END LOOP;
END $$;

COMMIT;
